# Generated by Django 5.2.1 on 2025-06-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_slug', models.SlugField(max_length=100, unique=True)),
                ('video_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('arvan_channel_title', models.CharField(max_length=100)),
                ('arvan_channel_id', models.CharField(max_length=100)),
                ('watermark', models.CharField(blank=True, max_length=100, null=True)),
                ('watermark_area', models.CharField(blank=True, choices=[('center', 'CENTER'), ('fix_top_left', 'FIX_TOP_LEFT'), ('fix_top_right', 'FIX_TOP_RIGHT'), ('fix_top_center', 'FIX_TOP_CENTER'), ('fix_bottom_left', 'FIX_BOTTOM_LEFT'), ('fix_bottom_right', 'FIX_BOTTOM_RIGHT'), ('fix_bottom_center', 'FIX_BOTTOM_CENTER'), ('animate_left_to_right', 'ANIMATE_LEFT_TO_RIGHT'), ('animate_top_to_bottom', 'ANIMATE_TOP_TO_BOTTOM')], max_length=30, null=True)),
            ],
        ),
    ]
