# Generated by Django 5.2.1 on 2025-06-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='arvan_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='arvan_channel_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
